### ISSUE TITLE
ERROR  require() of ES Module

### ISSUE THREAD

**Issue by ilyaDegtyarenko** [nuxt-community/sitemap-module#294]
I get an error after installing this package

```
ERROR  require() of ES Module .../node_modules/string-width/index.js from .../node_modules/wide-align/align.js not supported.                 
Instead change the require of index.js in.../node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.

Instead change the require of index.js in node_modules/wide-align/align.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (node_modules/wide-align/align.js:2:19)
  at Object.<anonymous> (node_modules/gauge/render-template.js:2:13)
  at Object.<anonymous> (node_modules/gauge/plumbing.js:3:22)
  at Object.<anonymous> (node_modules/gauge/index.js:2:16)
  at Object.<anonymous> (node_modules/npmlog/log.js:3:13)
  at Object.<anonymous> (node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js:23:13)
  at Object.<anonymous> (node_modules/@vercel/nft/out/analyze.js:22:40)
  at Object.<anonymous> (node_modules/@vercel/nft/out/node-file-trace.js:31:35)
  at Object.<anonymous> (node_modules/@vercel/nft/out/index.js:22:25) 

```

My package.json

```
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "nuxt dev --dotenv .env.development --open --port=3001",
    "build": "nuxt build --dotenv .env.development-build",
    "build-dev": "nuxt build --dotenv .env.dev && rm -rf .output-dev && mv .output .output-dev",
    "build-prod": "nuxt build --dotenv .env.prod && rm -rf .output-prod && mv .output .output-prod",
    "generate": "nuxt generate",
    "generate-serve": "nuxt generate && npx serve .output/public",
    "serve": "npx serve .output/public",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "cleanup": "nuxi cleanup",
    "lint": "eslint --ext \".ts,.js,.vue\" --ignore-path .gitignore .",
    "lint-fix": "eslint --fix --ext \".ts,.js,.vue\" --ignore-path .gitignore .",
    "type-check": "tsc"
  },
  "devDependencies": {
    "@nuxt/devtools": "^1.0.8",
    "@nuxtjs/eslint-config-typescript": "^12.1.0",
    "autoprefixer": "^10.4.17",
    "eslint": "^8.56.0",
    "eslint-plugin-nuxt": "^4.0.0",
    "nuxt": "^3.10.1",
    "postcss": "^8.4.35",
    "sass": "^1.70.0",
    "sass-loader": "^14.1.0",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.3.3",
    "vue": "^3.4.18",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "@nuxtjs/sitemap": "^5.1.0",
    "@pinia/nuxt": "^0.5.1",
    "pinia": "^2.1.7"
  },
  "engines": {
    "node": "18"
  }
}
```

**Comment by NicoPennec** [comment]
Hi @ilyaDegtyarenko 
This repository is now for the legacy sitemap module on Nuxt 2.x

Go to the new repositoty about Nuxt 3.x here: https://github.com/nuxt-modules/sitemap
